# -*- coding: utf-8 -*-
"""decision tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJZh-ER_2OEnqnBVne6jXXBtpxHp21Z_
"""

1)import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder



print("Upload iris.csv file")
from google.colab import files
uploaded = files.upload()


iris = pd.read_csv("/content/iris (1).csv")

print("\nIRIS Dataset Preview:")
print(iris.head())


X = iris.iloc[:, :-1]
y = iris.iloc[:, -1]


le = LabelEncoder()
y = le.fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)


model = DecisionTreeClassifier()
model.fit(X_train, y_train)


y_pred = model.predict(X_test)


print("\nIRIS Accuracy:", accuracy_score(y_test, y_pred))
print("\nIRIS Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

2)print("\nUpload drug.csv file")
uploaded = files.upload()


drug = pd.read_csv("drug.csv")

print("\nDrug Dataset Preview:")
print(drug.head())


X = drug.iloc[:, :-1]
y = drug.iloc[:, -1]

le = LabelEncoder()
for column in X.columns:
    if X[column].dtype == 'object':
        X[column] = le.fit_transform(X[column])


y = le.fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)


model = DecisionTreeClassifier()
model.fit(X_train, y_train)


y_pred = model.predict(X_test)


print("\nDrug Dataset Accuracy:", accuracy_score(y_test, y_pred))
print("\nDrug Dataset Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
